import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Cardiothoracic Surgery ST1 2026 — national run-through programme. Selection is
// MSRA + portfolio-based interview. No publicly published per-band numeric scoring
// matrix, so configured as evidence-based for users to upload supporting evidence.
export const CARDIOTHORACIC_ST1_2026: SpecialtyConfig = {
  key: 'cardiothoracic_st1_2026',
  name: 'Cardiothoracic Surgery ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/cardiothoracic-surgery-st1-2026',
  sourceLabel: 'NHS England — Cardiothoracic Surgery ST1 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'cardiothoracic_experience_cap',
      label: 'Prior cardiothoracic experience ≤18 months WTE',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Combined whole-time-equivalent experience in cardiac surgery, thoracic surgery, congenital cardiac surgery and cardiothoracic transplantation must not exceed 18 months by application closing date. Direct-from-Foundation applicants meet this trivially; relevant mainly for IMGs, LAT/trust-grade, or returners.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate & Intercalated Degrees',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'BSc/BA/BMedSci (intercalated, with classification), MSc/MA/MRes, MD, PhD/DPhil. Cardiac/cardiovascular research degrees particularly valued.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'PubMed-indexed first/joint-first author original research scores highest. Cardiothoracic-related publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. SCTS, EACTS, AATS).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. Cardiothoracic-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching sessions, PG Cert in Medical Education or equivalent.',
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Committee roles, society leadership, NHS management training, healthcare leadership programmes.',
    },
    {
      key: 'commitment_cardiothoracic',
      label: 'Commitment to Cardiothoracic Surgery',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Cardiothoracic taster/elective, SCTS membership (including student/junior membership), basic surgical skills courses, cardiothoracic-specific courses, attendance at SCTS Annual Meeting or regional cardiothoracic meetings, surgical electives, validated logbook entries from cardiothoracic exposure.',
    },
  ],
}
