import type { SpecialtyConfig } from './types'
import { UNIVERSAL_ESSENTIALS } from './shared'

// Neurosurgery ST1 2026 — national run-through programme (Yorks & Humber lead).
// Selection: MSRA (40%) + portfolio-based interview (60%). The detailed shortlisting
// matrix is published only via the Oriel applicant pack and not as a public per-band
// numeric scheme, so configured as evidence-based for users to upload supporting
// evidence against each domain.
export const NEUROSURGERY_ST1_2026: SpecialtyConfig = {
  key: 'neurosurgery_st1_2026',
  name: 'Neurosurgery ST1',
  cycleYear: 2026,
  totalMax: 0,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/neurosurgery-st1-2026',
  sourceLabel: 'NHS England — Neurosurgery ST1 2026 Person Specification',
  isOfficial: true,
  scoringType: 'evidence',
  isEvidenceOnly: true,
  domains: [
    ...UNIVERSAL_ESSENTIALS,
    {
      key: 'neurosurgery_experience_cap',
      label: 'Prior clinical experience ≤24 months WTE',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Total post-Foundation clinical experience (whole-time-equivalent, excluding Foundation modules) must not exceed 24 months by post start date. Direct-from-Foundation applicants meet this trivially; relevant mainly for IMGs, LAT/trust-grade, or returners.',
    },
    {
      key: 'neurosurgery_logbook',
      label: 'Validated surgical logbook',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'essential',
      notes: 'Validated logbook documentation of surgical exposure (eLogbook consolidation report or equivalent). Listed as a specialty-specific essential in the 2026 person spec.',
    },
    {
      key: 'qualifications',
      label: 'Postgraduate & Intercalated Degrees',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'BSc/BA/BMedSci (intercalated, with classification), MSc/MA/MRes, MD, PhD/DPhil. Neuroscience-related degrees particularly valued.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Up to five peer-reviewed publications can be listed on the application. PubMed-indexed first/joint-first author original research scores highest. Neurosurgery-related publications particularly valued.',
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Oral and poster presentations at international, national, regional and local meetings (e.g. SBNS, Tessa Jowell, EANS).',
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Closed-loop QI/audit cycles with documented change and re-audit. Neurosurgery-themed projects particularly valued.',
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Organised teaching programmes with feedback, regular teaching sessions, PG Cert in Medical Education or equivalent.',
    },
    {
      key: 'leadership_management',
      label: 'Leadership & Management',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Committee roles, society leadership, formal management training. NHS management understanding valued.',
    },
    {
      key: 'commitment_neurosurgery',
      label: 'Commitment to Neurosurgery',
      maxPoints: 0,
      scoringRule: 'highest',
      bands: [],
      criteriaType: 'desirable',
      isEvidenceOnly: true,
      notes: 'Neurosurgery taster/elective, SBNS membership, basic surgical skills courses, neuro-related courses (e.g. ATLS, microsurgery), clinical exposure to neurosurgery / neurology / neuro-ICU. Realistic insight into the personal demands of the specialty.',
    },
  ],
}
