import type { SpecialtyConfig } from './types'

export const PUBLIC_HEALTH_ST1_2026: SpecialtyConfig = {
  key: 'public_health_st1_2026',
  name: 'Public Health ST1',
  cycleYear: 2026,
  totalMax: 26,
  source: 'https://medical.hee.nhs.uk/medical-training-recruitment/medical-specialty-training/person-specifications/person-specifications-2026/public-health-st1-2026',
  sourceLabel: 'NHS England — Public Health ST1 2026 Person Specification',
  isOfficial: false,
  domains: [
    {
      key: 'qualifications',
      label: 'Postgraduate Degrees & Qualifications',
      maxPoints: 4,
      scoringRule: 'highest',
      bands: [
        { label: 'PhD/MD by research', points: 4 },
        { label: 'Masters (MSc/MA/MRes, 8+ months) — especially MPH or MSc in Public Health / Epidemiology', points: 3 },
        { label: 'PG diploma/certificate', points: 1 },
      ],
      notes: '⚠️ Public Health ST1 2026 selection uses Stage 1 computer-based tests (Watson-Glaser critical reasoning 25% + RANRA numerical 25% + SJT 50%) followed by a Stage 2 selection centre — NO portfolio self-assessment at application. This config is for portfolio-building reference only.',
    },
    {
      key: 'publications',
      label: 'Publications',
      maxPoints: 6,
      scoringRule: 'highest',
      bands: [
        { label: 'First/joint-first author original research (PubMed-indexed or in press)', points: 6 },
        { label: 'Co-author original research (PubMed-indexed)', points: 4 },
        { label: 'Book chapter or multiple other publications (2+)', points: 4 },
        { label: 'Single publication (editorial/review/case report/letter)', points: 2 },
        { label: 'Published abstract or non-peer-reviewed article', points: 1 },
      ],
    },
    {
      key: 'presentations',
      label: 'Presentations & Posters',
      maxPoints: 4,
      scoringRule: 'highest',
      bands: [
        { label: 'Oral 1st/2nd author national/international', points: 4 },
        { label: 'Poster 1st/2nd author national/international', points: 3 },
        { label: 'Oral or poster regional', points: 2 },
        { label: 'Oral or poster local', points: 1 },
      ],
    },
    {
      key: 'quality_improvement',
      label: 'Quality Improvement / Audit / Service Evaluation',
      maxPoints: 4,
      scoringRule: 'highest',
      bands: [
        { label: 'Led complete QI/audit cycle with documented change and re-audit (closed loop)', points: 4 },
        { label: 'All stages of a single QI/audit cycle', points: 3 },
        { label: 'Participated in QI/audit with a clearly defined role', points: 2 },
        { label: 'Minor participation only', points: 1 },
      ],
    },
    {
      key: 'teaching',
      label: 'Teaching Experience',
      maxPoints: 3,
      scoringRule: 'highest',
      bands: [
        { label: 'Organised or led formal teaching programme 3+ months with feedback', points: 3 },
        { label: 'Regular formal teaching sessions with documented feedback', points: 2 },
        { label: 'Occasional formal teaching with some evidence', points: 1 },
      ],
    },
    {
      key: 'commitment_public_health',
      label: 'Commitment to Public Health',
      maxPoints: 5,
      scoringRule: 'cumulative_capped',
      isCheckbox: true,
      bands: [
        { label: 'MFPH Part A (DFPH) pass or attempt', points: 2 },
        { label: 'Public health taster week, attachment or internship', points: 1 },
        { label: 'Member of Faculty of Public Health (FPH) or public health society', points: 1 },
        { label: 'National public health conference attended (1st)', points: 1 },
        { label: 'National public health conference attended (2nd)', points: 1 },
        { label: 'Health policy, epidemiology or global health project (outside standard training)', points: 1 },
        { label: 'Health promotion, public health volunteering or advocacy work', points: 1 },
      ],
      notes: 'Points capped at 5.',
    },
  ],
}
